## TP1 Traitement du signal - Prise en main de Python pour faire du traitement du signal

## Notebook Jupyter et Python

## Quelques rappels de Python utiles pour faire du traitement du signal

### La bibliothèque numpy

La bibliothèqe [numpy](https://numpy.org/) permet de manipuler des matrices et des tableaux à n dimensions dans Python. Elle est particulièrement utilisée pour du calcul scientifique et en traitement du signal et des images. 

Les vecteurs et matrices sont des [numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) de 1 et 2 dimensions. 

Quelques exemples d'opérations de base entre vecteurs et matrices sont présentées ci-dessous. 

In [1]:
import numpy as np

vect1 = np.array([1,2,3,4])
print(vect1)
print(vect1[1:3]) #vect[i:j] permet d'accéder à l'ensemble des éléments de rang i (inclus) à j (non inclus)
print()

mat1 = np.array([[1,2],[3,4]])
print(mat1)
mat2 = np.array([[4,5],[6,7]])
print(mat2[1,1]) #affichage de l'élément (1,1) soit l'élément appartenant à la deuxième ligne et la deuxième colonne
print()

mat3 = mat1 + mat2
print(mat3)
print()

mat3 = mat2-mat1
print(mat3)
print()

mat3 = mat1*mat2 #multiplication des éléments des deux matrices terme à terme
print(mat3)
print()

mat3 = mat2/mat1 #division des éléments des deux matrices terme à terme
print(mat3)
print()

mat3 = np.dot(mat1,mat2) #produit matriciel
print(mat3)
print()

[1 2 3 4]
[2 3]

[[1 2]
 [3 4]]
7

[[ 5  7]
 [ 9 11]]

[[3 3]
 [3 3]]

[[ 4 10]
 [18 28]]

[[4.   2.5 ]
 [2.   1.75]]

[[16 19]
 [36 43]]



**ACTION :** Créer une matrice A de taille 4x4 (avec numpy) que vous peuplez aléatoirement. Accéder et afficher : 
- la première ligne de A 
- la quatrième colonne de A 
- les trois premiers éléments de la quatrième ligne de A 

In [2]:
import numpy as np

A = np.random.rand(4,4) # matrice 4x4 aléatoire (loi uniforme)
print(A)
print()


# Rq1. : 1er index matrice : (0,0)
# Rq2. : (a,b) avec a indice des lignes, b indice des colonnes  
print( A[0, :]) # 1ere ligne de A
print()

print( (A[:,3]) ) # 4e colonne de A
print()

print( (A[3, [i for i in range(0,3)] ]) ) # 3 premiers éléments de la 4e ligne de A
print()

print( (A[3,:3]) ) # 3 premiers éléments de la 4e ligne de A
print()




[[0.30681422 0.72940089 0.43568654 0.61322331]
 [0.90489697 0.75364238 0.90634926 0.17877719]
 [0.58427426 0.74213421 0.41676705 0.98197071]
 [0.18371287 0.14279181 0.75306635 0.15113305]]

[0.30681422 0.72940089 0.43568654 0.61322331]

[0.61322331 0.17877719 0.98197071 0.15113305]

[0.18371287 0.14279181 0.75306635]

[0.18371287 0.14279181 0.75306635]



### La bibliothèque matplotlib

La bibliothèque [matplotlib](https://matplotlib.org/) permet de visualiser des données sous forme de graphique. Elle nous sera utile pour afficher les signaux 1D et les signaux 2D (sous forme d'image). 

**ACTION  :** L’affichage d’un vecteur se fait par l’intermédiaire de la fonction [plot](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.plot.html) très utile pour obtenir des courbes de différentes fonctions planes. La commande matplotwidget permet de manipuler les figures dans le notebook. 
Tester le code dans les cellules ci-dessous. 

In [8]:
%matplotlib widget 
# gere la barre latérale (zoom, etc.) Rq. : si pb à la place de "widget" utiliser "inline"

import matplotlib.pyplot as plt
import math

x = np.array([i for i in range(0,10,3)]) #création d'un vecteur qui contient des éléments de 0 à 10 (non inclus) avec un pas de 3
plt.plot(x) #affichage par défaut du vecteur

plt.figure() #création d'une nouvelle figure
plt.plot(x,'r*') #affichage du vecteur en rouge avec des marqueurs "étoiles"

y = np.random.rand(4) #création d'un vecteur de taille 4 avec des éléments aléatoires compris entre 0 et 1. 

plt.figure()
plt.plot(y,'o-') #affichage du vecteur y avec la couleur par défaut, des marqueurs '+'. Les points sont reliés. 
plt.plot(x,y,'g*-') #affichage de la fonction y = f(x) en vert. Les points sont des marqueurs '*' et ils sont reliés. 
#si on ne crée pas une nouvelle figure avant de dessiner (plot), la courbe est dessinée dans la figure précédente (en superposition)

plt.figure()
z = np.linspace(-math.pi, math.pi, 10)
plt.plot(z, np.sin(z), 'r*-')
plt.title("Fct sinus")
plt.legend(["Sinus"])


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

**ACTION :** L’affichage d’une matrice correspond lui à celui d’une image. Chaque élément *(m, n)* de la matrice est considéré comme étant la valeur du pixel *(m, n)* auquel il est associé. Vérifier ceci en entrant les commandes suivantes.

In [9]:
a = np.random.rand(10,10)*10 #matrice 10x10 avec des éléments de 0 à 10
a = np.exp(a) #pour obtenir de plus grands écarts entre les éléments de la matrice a

print(np.max(a), np.min(a))
print()

plt.figure() #nouvelle figure
plt.imshow(a) #afficher l'image correspondant à la matrice a
plt.colorbar()

21192.35928858608 1.0036813905383173



Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Par défaut, *imshow* utilse la colormap *viridis* si la matrice est 2D. On associe généralement ce type de matrice à une image en niveau de gris. Il faut donc spécifier la colormap.

In [11]:
#grey_map=plt.cm.gray #définition de la colormap en niveau de gris (existe déjà dans la bibliothèque)
grey_map=plt.cm.magma #définition de la colormap "magma" 
plt.figure()
plt.imshow(a, grey_map) #affichage avec cette color map
plt.colorbar()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

## Premiers pas en traitement du signal avec Python

### Premier signal

Un signal 1D peut être vu comme un vecteur où la durée d'observation est la taille du vecteur (nombre d'éléments).

**ACTION :** Ecrire une fonction *my_impulse* qui renvoie un signal impulsion avec 2 arguments en entrée, un pour définir la durée d’observation du signal, un autre pour la position de l’impulsion. Tester la fonction en affichant le résultat avec les fonctions *plot* et *stem*.

In [13]:
def my_impulse(duree, position) :
    s = np.zeros(duree)
    s[position] = 1
    return s
    
s = my_impulse(200,56)
plt.figure()
plt.plot(s, '*-')
plt.title("My Impulse")

plt.figure()
plt.stem(s)
plt.title("My Impulse")

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0.5, 1.0, 'My Impulse')

### Signaux sinusoïdaux

**ACTION :** Créer deux signaux sinusoïdaux de fréquence *20 Hz* et *80 Hz* respectivement échantillonnés à *200 Hz*. L'échantillonnage est vu ici comme la durée entre deux valeurs du vecteur contenant les valeurs du signal. Dit autrement, le pas entre deux observations est *Te = 1/Fe*. La durée d'observation est à définir. 
Visualiser ces deux signaux.

In [16]:
Fe = 200
Te = 1/Fe
n1 = np.arange(0,0.2,Te)

f1 = 20
s1 = np.sin(2*np.pi*f1*n1)

plt.figure()
plt.plot(n1,s1,'r*-')
plt.legend(['s1'])

plt.figure()
plt.stem(n1,s1,'r*-')
plt.legend(['s1'])

f2 = 80
s2 = np.sin(2*np.pi*f2*n1)

plt.figure()
plt.plot(n1,s2,'r*-')
plt.legend(['s2'])

plt.figure()
plt.stem(n1,s2,'r*-')
plt.legend(['s2'])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

### Analyse temporelle (échantillonnage)

**ACTION :** Conserver un échantillon sur deux pour les deux signaux, observer les deux nouveaux signaux (vous pouvez les superposer aux signaux précédents dans une autre couleur), conclure.

In [22]:
Fe2 = Fe/2
Te2 = 1/Fe2
n2 = np.arange(0,0.2,Te2)

f1 = 20
s3 = np.sin(2*np.pi*f1*n2)

plt.figure()
plt.plot(n1,s1,'r*-')
plt.plot(n2,s3,'g+-')
plt.legend(['s1', 's3'])
plt.title('sin à 20Hz échantillonné à 200Hz et 100Hz ')


#plt.figure()
#plt.stem(n1,s1,'r')
#plt.stem(n2,s3,'g')
#plt.legend(['s1', 's3'])

f2 = 80
s4 = np.sin(2*np.pi*f2*n2)

plt.figure()
plt.plot(n1,s2,'r*-')
plt.plot(n2,s4,'g+-')
plt.legend(['s2', 's4'])
plt.title('sin à 80Hz échantillonné à 200Hz et 100Hz ')

#plt.figure()
#plt.stem(n1,s2,'r')
#plt.stem(n2,s4,'g')
#plt.legend(['s2', 's4'])

plt.figure()
plt.plot(n2,s3,'r*-')
plt.plot(n2,s4,'g+-')
plt.legend(['s3', 's4'])
plt.title('sin à 20Hz et sin à 80Hz échantillonnés à 100Hz ')






Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0.5, 1.0, 'sin à 20Hz et sin à 80Hz échantillonnés à 100Hz ')

**REPONSE :** *s4* est devenu quasi identique à *s3* (à un déphasage prêt). Dans *s4* il y a trop peu d'échantillons pour représenter les oscillations présentent originalement dans *s2* (on verra dans le prochain TP que le Th. de Shannon n'est pas respecté pour obtenir *s4*). On peut dire aussi que le sous-échantillonnage a en quelque sorte "lissé" le signal *s2*.  

**ACTION :** Charger les signaux stockés sous forme de vecteur dans les fichiers csv *signal_inconnu* et *signal_inconnu2* grâce à la fonction [*genfromtxt*](https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html) de la bibliothèque numpy. Afficher-les. 

In [23]:
ss1 = np.genfromtxt('signal_inconnu1.csv',delimiter=',') #chargement du premier signal inconnu
ss2 = np.genfromtxt('signal_inconnu2.csv',delimiter=',') #chargement du deuxième signal inconnu
plt.figure()
plt.plot(ss1,'*r-')
plt.plot(ss2,'+g-')
plt.legend(['ss1', 'ss2'])
plt.title('signaux inconnus')


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0.5, 1.0, 'signaux inconnus')

**ACTION :** Conserver un seul échantillon sur deux des deux signaux précédents et les afficher à nouveau. Utiliser la fonction [*arange*](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html) pour ne conserver qu'un seul élément sur deux d'un tableau. 

In [25]:
n = np.arange(0,len(ss1),2)

ss1_2 = np.take(ss1,n)

plt.figure()
plt.plot(ss1_2,'*r-')

ss2_2 = np.take(ss2,n)
plt.plot(ss2_2,'+g-')

plt.legend(['ss1_2', 'ss2_2'])
plt.title('Fonctions inconnues sous-échantillonnées (facteur 2)')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0.5, 1.0, 'Fonctions inconnues sous-échantillonnées (facteur 2)')

**ACTION :** Interpréter les courbes obtenues. Que faut-il faire avant de sous-échantillonner ? 

**REPONSE :** *ss1_2* et *ss2_2* se "ressemblent" après sous-échantillonnage (d'un facteur 2). Exactement le sous-échantillonnage a peu modifié l'allure de *ss2*, mais surtout celle de *ss1* : *ss1_2* varie moins, le sous-échantillonage a donc agi comme un filtre lisseur. Cependant en pratique il faut mieux préalablement lisser un signal avant de le sous-échantillonner, afin d'éviter de prélever (au hasard) des échantillons possiblement bruités.    
(les aspects de l'analyse spectrale seront abordés dans le prochain TP). 

**ACTION :** Charger le signal stocké dans le fichier *signal_inconnu3.csv*. Celui-ci contient les échantillons d’un signal bruité. On propose de filtrer ce signal avec une fenêtre ou moyenne glissante de grande taille, écrire la fonction de filtrage correspondante. Visualiser le résultat et jouer sur la taille de la fenêtre. 

In [33]:
ss5 = np.genfromtxt('signal_inconnu3.csv',delimiter=',')
plt.figure()
plt.plot(ss5,'r*-')
plt.legend(['ss5'])
plt.title('Signal inconnu')

taille_filtre = 101 #plutot prendre une valeur impaire
h = np.ones(taille_filtre)  / taille_filtre
plt.figure()
plt.stem(h)
plt.legend(['h'])
plt.title('Réponse impulsionnelle du filtre')


ss6 = np.convolve(ss5, h)

#taille(ss6) = taille(ss5)+ taille(h) + 1
#ici on choisit de couper ss6 de façon à le superposer à ss5
#ss7 = ss6( (taille_filtre+1)/2 : size(f,2) +1 - ((taille_filtre+1)/2) );
 
plt.figure()
plt.plot(ss6,'g*-');
plt.legend(['ss6'])


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

**Action :** Afficher la taille de *ss5*, *h* et *ss6* (signal filtré). Etablir le lien entre ses tailles. Afficher *ss6* en le superposant à *ss5*. 

**Réponse :** Le signal *ss6* est plus large que celui *ss5* du fait de l'entrée/sortie du filtre *h* lors de la convolution. C'est l'effet de bord du filtre. Si le filtre *h* est de taille impaire et centrée, on considère que pendant la convolution, lors du glissement du filtre *h* sur *ss5*, une demi partie du filtre *h* va entrer dans *ss5*, et une demi partie du filtre *h* va en sortir. En dehors du signal *ss5*, les échantillons supplémentaires de signal, nécessaires pour la convolution avec *h*, sont considérés égaux à 0.

In [43]:
taille_ss5 = np.size(ss5)
taille_h = np.size(h) 
taille_ss6 = np.size(ss6)

taille_ss6b = np.size(ss5)+ np.size(h) - 1

print(taille_ss5, taille_h, taille_ss6, taille_ss6b)

# On obtient ss7 en coupant ss6 de façon à le superposer à ss5
# On coupe ss6 au début et à la fin, en lui ôtant à chaque fois 
# une nombre d'échantillons égal à une demi-taille du filtre

n = range( int((taille_h+1)/2)-1, taille_ss6 - int((taille_h+1)/2) + 1)

ss7 = np.take(ss6, n)

taille_ss7 = np.size(ss7)
print(taille_ss7)
    
plt.figure()
plt.plot(ss5, 'r*-');
plt.plot(ss7, 'g*-');
plt.legend(['ss5','ss7'])


2001 101 2101 2101
2001


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …